feign:
  client:
    config:
      default:
        connectTimeout: 500
        readTimeout: 500
        loggerLevel: full
        default-request-headers:
          appkey: ${KIS_APP_KEY}
          appsecret: ${KIS_SECRET_KEY}
          tr_id: FHKST03010200

apis:
  kis:
    url: https://openapi.koreainvestment.com:9443

---
spring:
  config:
    activate:
      on-profile: test

apis:
  kis:
    url: http://localhost:${wiremock.server.port}
