feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 10000
        loggerLevel: full
        default-request-headers:
          appkey: ${KIS_APP_KEY}
          appsecret: ${KIS_SECRET_KEY}
          tr_id: FHKST03010200

apis:
  kis:
    url: https://openapi.koreainvestment.com:9443

logging:
  level:
    com:
      guide:
        openfeign:
          infra: DEBUG
---
spring:
  config:
    activate:
      on-profile: test

# SQL init log
logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG

apis:
  kis:
    url: http://localhost:${wiremock.server.port}
