spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/trading?serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: root
    password: root