spring:
  profiles:
    include:
      - auth
      - chart

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8641/trading?serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: root
    password: root

    jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

data-processing:
  target-stock-codes:
    024950, 017390, 016710, 293780, 164060,
    288620, 059090, 206560, 036030, 086520,
    001270, 001200, 001630, 001570, 001560,
    405000, 405100, 405920, 389260, 388050,
    382840, 383310, 378800, 376930, 377030,
    344860, 347000, 318160, 315640, 314140
