spring:
  profiles:
    include:
      - auth

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8641/trading?serverTimezone=Asia/Seoul
    username: root
    password: root

    jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always